# llmify_config.yaml
# Configuration to ignore unnecessary files and directories for LLMify-Code.

ignored_dirs:
  - node_modules
  - logs
  - config
  - .git
  - .venv
  - venv
  - __pycache__
  - .pytest_cache

ignored_files:
  - .dockerignore
  - .env
  - .gitignore
  - .eslintrc.json
  - .prettierignore
  - .prettierrc
  - package.json
  - yarn.lock
  - "*.pyc"
  - "*.pyd"
  - "*.so"
  - "*.log"
